version: "3.8"
networks:
  external:
    driver: bridge
    internal: false
volumes:
  php-fpm-socket:
  db-store:
  db-test-store:
  minio-store:
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    volumes:
      - .:/var/www/html
      - php-fpm-socket:/var/run/php-fpm
    environment:
      TZ: ${TZ:-Asia/Hanoi}
  nginx_frontend:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx_frontend
    environment:
      TZ: ${TZ:-Asia/Hanoi}
    volumes:
      - ./frontend:/var/www/html/frontend
      - ${WEB_DEFAULT_CONF:-./docker/nginx/default.conf}:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONTEND_PORT:-18080}:8080
